config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  
  devise_scope :user do
      root to: 'users#show'
  end

  namespace :admins do

    resources :files do
      collection do
        get :update_file_order
      end
    end

    resources :users do
      collection do
        get :profile
      end
    end

    resources :courses do
      collection do
        get :info_courses
        get :specific_course
        get :create
      end
    end

    resources :attachments do
      collection do
        get :create
      end
    end

    resources :modulos do
      collection do
        get :create
      end
    end

    resources :estudianterespondes
    resources :preguntas
    resources :respuestas
    resources :evaluacions do
      collection do
        get :create_evaluacion
      end
    end

  end
  
  get 'users/:user_id' => 'users#profile', :via => [:post], :as => :profile
  get 'cursos/:id' => 'usercourses#show', :via => [:POST], :as => :mycourses
  get 'modulos/:modulo_id' => 'courses#info_courses', :via => [:post], :as => :courses
  get 'courses/:course_id' => 'courses#specific_course', :via => [:post], :as => :specific_course
  get 'courses/:course_id/attachment/:course_attachment_id' => 'attachments#new', :via => [:post], :as => :new_attachment
  get 'files' => 'files#show', :via => [:get], :as => :convert_attachment
  get 'courses' => 'courses#nocourses', :via => [:get], :as => :nocourses
  get 'evaluacion/:course_id' => 'evaluacions#show', :as => :show_evaluaciones
  get '/respondes/' => 'estudianterespondes#new', :as => :estudiante_responde
  resources :estudianterespondes
  resources :modulos
  resources :courses
  resources :attachments
  resources :evaluacions
  resources :preguntas
  resources :respuestas
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
  has_many :courses
  has_many :user_courses
end

app/controllers/admins/modulos_controller.rb
class Admins::ModulosController < ApplicationController

  def new
    @modulo = Modulo.new
  end

  def create
    @modulo = Modulo.new(modulo_params)
    if @modulo.save
        redirect_to admins_user_path(:id => current_user.id)
    else
      render 'new'
    end
  end


  private
  def modulo_params
   params.require(:modulo).permit(:nombre, :descripcion)
  end
end

app/controllers/modulos_controller.rb
class ModulosController < ApplicationController

  def show
    @modulo = Modulo.all
  end

  

end

app/views/modulos/show.html.haml
%html
  %head
  %body 
    .col-xs-12
      %ul{class: "nav nav-tabs navbar-default"}
        %li{role: "presentation", class: "active"}
          = link_to "home", root_path 
        - if current_user
          %li{role: "presentation"}
            =link_to "Profile", profile_path(:user_id => current_user.id)
          %li{role: "presentation"}
            = link_to "Mis cursos", mycourses_path(:id => current_user.id)
          %li{role: "presentation"}
            = link_to "Comunidad"
          %li{role: "presentation"}
            = link_to "Mensajes"
          %li{role: "presentation"}
            = link_to "Soporte"
        %ul{class: "nav navbar-right"}
          %li{role: "presentation", class: "active"}
            - if current_user
              = link_to current_user.email,  destroy_user_session_path, :method => :DELETE
            - else
              = link_to "Login", new_user_session_path 
    -if current_user
      .container-fluid
        .col-xs-12
          %h1 Welcome
        .col-xs-4
          %h2 Bienvenida
        .col-xs-8    
          %h1 Cursos
          - @modulo.each do |c|
            .col-xs-12
              %hr
              %h2
            - if  current_user
              = link_to c.nombre, courses_path(:modulo_id => c.id)
              %p= c.descripcion
              %p= c.created_at
            - else
              = link_to c.nombre, new_user_session_path  
              %p= c.descripcion
              %p= c.created_at
      .col-xs-12
        %hr
      .col-xs-6.col-xs-offset-5
        %h3 deslogue
  %footer