config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  
  devise_scope :user do
      root to: 'users#show'
  end

  namespace :admins do

    resources :files do
      collection do
        get :update_file_order
      end
    end

    resources :users do
      collection do
        get :profile
      end
    end

    resources :courses do
      collection do
        get :info_courses
        get :specific_course
        get :create
      end
    end

    resources :attachments do
      collection do
        get :create
      end
    end

    resources :modulos do
      collection do
        get :create
      end
    end

    resources :estudianterespondes
    resources :preguntas
    resources :respuestas
    resources :evaluacions do
      collection do
        get :create_evaluacion
      end
    end

  end
  
  get 'users/:user_id' => 'users#profile', :via => [:post], :as => :profile
  get 'cursos/:id' => 'usercourses#show', :via => [:POST], :as => :mycourses
  get 'modulos/:modulo_id' => 'courses#info_courses', :via => [:post], :as => :courses
  get 'courses/:course_id' => 'courses#specific_course', :via => [:post], :as => :specific_course
  get 'courses/:course_id/attachment/:course_attachment_id' => 'attachments#new', :via => [:post], :as => :new_attachment
  get 'files' => 'files#show', :via => [:get], :as => :convert_attachment
  get 'courses' => 'courses#nocourses', :via => [:get], :as => :nocourses
  get 'evaluacion/:course_id' => 'evaluacions#show', :as => :show_evaluaciones
  get '/respondes/' => 'estudianterespondes#new', :as => :estudiante_responde
  resources :estudianterespondes
  resources :modulos
  resources :courses
  resources :attachments
  resources :evaluacions
  resources :preguntas
  resources :respuestas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :user_courses
  has_many :evaluacion_estudiantes
  has_many :estudianterespondes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  def index
    @users = User.all
    @courses = Course.all
    @modulos = Modulo.all
  end

  def show
    @users = User.all
    @courses = Course.all
    @modulos = Modulo.all
  end

  def profile
    @information = User.find_by_id(params[:user_id])
  end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @courses = Course.all
    @modulos = Modulo.all
  end

  def show
    @users = User.all
    @courses = Course.all
    @modulos = Modulo.all
  end

  def profile
    @information = User.find_by_id(params[:user_id])
  end
end

app/views/admins/users/profile.html.haml
%html
  %head
  %body
  - if current_user
    .col-xs-12
      %ul{class: "nav nav-tabs navbar-default"}
        %li{role: "presentation", class: "active"}
          = link_to "home", admins_user_path(:id => current_user.id)
        - if current_user
          %li{role: "presentation"}
            =link_to "Profile", profile_admins_users_path(:user_id => current_user.id)
        %ul{class: "nav navbar-right"}
          %li{role: "presentation", class: "active"}
            - if current_user
              = link_to current_user.email,  destroy_user_session_path, :method => :DELETE
            - else
              = link_to "Login", new_user_session_path 
    .container-fluid
      .col-xs-12
        %h1 Welcome
      .col-xs-4
        %h2 Bienvenida
      .col-xs-8    
        %h1 Detalles del usuario
        .col-xs-4.col-xs-offset-8
          %h4
            = link_to "Editar Informacion", edit_user_registration_path(current_user)
        .col-xs-12
          %hr
          %h2 Email
          = link_to @information.email
          %h2 Creado
          = link_to @information.created_at
      .col-xs-12
        %hr
      .col-xs-6.col-xs-offset-5
        %h3 deslogue
  - else
    :javascript
      window.location.href = "/users/sign_in"
  %footer

app/views/admins/users/show.html.haml
.col-xs-12
  %h1 Welcome
.col-xs-4
  %h2 Bienvenida
.col-xs-8    
  .col-xs-8
    %h1 Cursos
  .col-xs-4
    = link_to "Agregar Nuevo", new_admins_modulo_path
.col-xs-8.col-xs-offset-3
  - @modulos.each do |c|
    %hr
    %h2
    - if current_user
      = link_to c.nombre, info_courses_admins_courses_path(:modulo_id => c.id)
      %button{type: "button", class: "btn btn-default"}
        %span{class: "glyphicon glyphicon-align-right"}
      %p= c.descripcion
      %p= c.created_at
    - else
      = link_to c.nombre, new_user_session_path  
      %p= c.descripcion
      %p= c.created_at
.col-xs-12
  %hr
.col-xs-6.col-xs-offset-5
  %h3 deslogue
%footer